#' ---
#' title:  "Basic Goodness-of-fit Diagnositic Plots"
#' author: "Certara PMxO R Tools Workstream"
#' date:   "`r format(Sys.Date(), '%d-%b-%Y')`"
#' output: rmarkdown::html_vignette
#'     
#' vignette: >
#'   %\VignetteIndexEntry{Basic Goodness-of-fit Diagnositic Plots}
#'   %\VignetteEngine{knitr::rmarkdown}
#'   %\VignetteEncoding{UTF-8}
#' ---

#+ echo=FALSE
knitr::opts_knit$set(root.dir=system.file("sample-data", package="ggcertara"))
knitr::opts_chunk$set(warning=FALSE, message=TRUE, comment="#>")
suppressPackageStartupMessages({
  library(ggplot2)
  library(ggcertara)
})
#+


#' # Basic usage
#'
#' In the most basic case, you simply need to call the function `gof()` from
#' within the directory that contains a model output table. For this example,
#' we don't have an actual model so we will use some sample data that has been
#' provided with this packaga and pretend that it is the  result of a model
#' fit. We check the current working directory and note that it contains a
#' single CSV file.
getwd()
dir()

#' This file was actually generated by NONMEM (using the statement `$TABLE
#' FILE=nmtable1.csv FORMAT=,1PE15.8 ...`).  It's contents look like this:
#+ echo=F
knitr::kable(head(nmtable1))


#' When called without a `data` argument, the `gof()` function will actually
#' search the current directory for a CSV file that looks like it contains the
#' information it requires (i.e., has columns `dv`, `pred`, `ipred` and so on;
#' the data will also be filtered on an `mdv` column, if present).
#' Alternatively, the `sdtab` file that is commonly used with PsN/Xpose will
#' also be detected.
#+ fig.width=6, fig.height=9
gof()

#' By default, the `gof()` function produces a figure with 6 panels arranged in
#' a 3-by-2 grid: DV vs. IPRED, DV vs. PRED, CWRES vs. PRED, CWRES vs. TIME,
#' CWRES vs. TAD, and absolute value of IWRES vs. IPRED. Note that all axes are
#' nicely labelled (though they lack units at this point). With this simple
#' function call, we have produced a report ready figure!

#' # Customizing the output

#' ## Data specification

#' While it is convenient to have the function automatically scan for data in
#' the current working directory, this may not always be the desired approach
#' and it is also possible to pass a standard `data.frame` to the `gof()`
#' function via the `data` argument.

#' The `gof()` function expects the dataset to contain standard column names:
#'
#'   - time:   Time (e.g., time since first dose)
#'   - tad:    Time after dose
#'   - dv:     Dependent variable
#'   - pred:   Population prediction
#'   - ipred:  Individual prediction
#'   - cwres:  Conditional weighted residual
#'   - iwres:  Individual weighted residual
#'
#' Not all of these need to be present, only those that are needed for the
#' disired plots (for instance, if no plots involving IWRES are requested, then
#' it does not need to be present). The column names must be in lower case.

#' We now read in the sample data used above and for the remainder of this
#' vignette we will pass this data to the `gof()` function. We remember to
#' convert the column names to lower case and to filter out only the rows that
#' contain observations (as indicated by MDV=0).
dat <- read.csv("nmtable1.csv")
names(dat) <- tolower(names(dat))
dat <- subset(dat, mdv==0)

#' ## Selecting panels

#' The `gof()` function can easily produce a variety of standard panels. The
#' panel are numbered.

#' Using the `panels` argument, single or multiple panels can be selected.  For
#' example, to prduce both a histogram and QQ-plot of CWRES, select panels 1
#' and 2:
#+ fig.width=6, fig.height=3
gof(dat, panels=1:2)

#' To obtain just a plot of DV vs. IPRED on log-log scale, select panel 5:
#+ fig.width=3, fig.height=3
gof(dat, panels=5)

#' Individual panels can also be obtain in 2 other ways.
#' The first is to select the desired panel from the list of panels returned by
#' `gof_list()` (which returns a list of all standard panels):
#+ fig.width=3, fig.height=3
p <- gof_list(dat)
p[[5]]

#' The other way is to use a named function:
#+ fig.width=3, fig.height=3
gof_dv_vs_ipred(dat, log_xy=T)

#' Note that individual panels are standard `ggplot` objects (that can be
#' further customized, modified, annotated, composed, etc.), while when
#' multiple panels are requested a `patchwork` object is returned (this can
#' also be further cutomized, see below).

#' ## Labels

default.labels

#' ## Changing aesthetics (colors, etc.)

theme_set(theme_certara())
gl <- guide_legend("Legend", title.position="top")

dat$outlier <- factor(abs(dat$cwres) > 2.5, labels=c("|CWRES| \U{2264} 2.5", "|CWRES| > 2.5"))

#' For a single panel, you can just modify the `ggplot` object:

g <- gof(dat, panels=3)

#+ fig.width=4, fig.height=4
g +
  aes(color=outlier, shape=outlier, size=outlier) +
  guides(colour=gl, shape=gl, size=gl) +
  scale_colour_manual(values=c("#2b398b", "#ee3124"))

#' For a `patchwork` object (multiple panels), you can do the same thing by
#' replacing the `+` operator with a `%`:

g <- gof(dat, panels=3:4)

#+ fig.width=6, fig.height=4
g &
  aes(color=outlier, shape=outlier, size=outlier) &
  guides(colour=gl, shape=gl, size=gl) &
  scale_colour_manual(values=c("#2b398b", "#ee3124"))

#' `patchwork` is smart enough to produce a single legend for both panels.

#' ## Adding geoms and annotations

g <- gof(dat, panels=10:11)

#+ fig.width=6, fig.height=3
g & geom_smooth(method="lm", color="#52ccbb", se=F, size=1)

g <- gof(dat, panels=5:6)

#+ fig.width=6, fig.height=3
g &
  geom_hline(yintercept=1.2, linetype="dashed") &
  geom_text(data=data.frame(x=Inf, y=1.2), aes(x=x, y=y),
    label="LLOQ = 1.2 ng/mL", hjust=1.1, vjust=-0.5, size=3)

#' # R session information

sessionInfo()


#+ echo=F
# vim: ts=2 sw=2 et
